name: 'fff-ir-lint'
description: 'check .ir files'
author: 'd2a <hi@d2a.io>'
inputs:
  token:
    required: true
    description: 'GitHub Repository Token'
  lint-path:
    required: true
    description: 'Path to linter without tailing /'
  files:
    required: true
    description: '.ir files to check'
runs:
  using: 'node16'
  main: 'dist/index.js'
